apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitemusic-webpage
  namespace: lab-docker
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: sitemusic
        image: docker.io/baimas/sitemusic-webpage:latest
        ports:
        - containerPort: 80

